name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: vuonghuuhung/g21-be:staging

      - name: Deploy to InfinityFree
        run: |
          docker login -u ${{ secrets.INFINITYFREE_USERNAME }} -p ${{ secrets.INFINITYFREE_PASSWORD }} ftp://185.27.134.34
          docker pull vuonghuuhung/g21-be:staging
          docker tag vuonghuuhung/g21-be:staging 185.27.134.34/g21-be:staging
          docker push 185.27.134.34/g21-be:staging
