name: Deploy to InfinityFree

on:
  push:
    branches:
      - staging-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: ./Dockerfile
          push: true
          tags: vuonghuuhung/g21-be:staging

      - name: Push to Repository
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag be-g21 ${{ secrets.DOCKER_USERNAME }}/be-g21:staging
          docker push ${{ secrets.DOCKER_USERNAME }}/be-g21:staging
          docker tag be-g21 g21-be.great-site.net/be-g21
          docker push g21-be.great-site.net/be-g21
