name: Build and Push to Docker Hub

on:
  push:
    branches:
      - staging-test

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: ./Dockerfile
          push: true
          tags: vuonghuuhung/g21-backend-image:staging

      - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'g21-be'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c87139734a204608a7924766f579d692 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e32fa43cd63144e18ce21fc8892c754f }}/vuonghuuhung/g21-backend-image:${{ github.sha }}'