# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - g21-be

on:
  push:
    branches:
      - staging-test
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://g21be.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_aa61053aeea04480a2622e2dd49bf5d9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_55de2f91d3c2492496fc07954202b03d }}

    - name: Copy .env.example to .env and update variables
      run: |
        cp .env.example .env
        sed -i "s/DB_HOST=127.0.0.1/DB_HOST=${{ secrets.DB_HOST }}/g" .env
        sed -i "s/DB_DATABASE=laravel/DB_DATABASE=${{ secrets.DB_DATABASE }}/g" .env
        sed -i "s/DB_USERNAME=root/DB_USERNAME=${{ secrets.DB_USERNAME }}/g" .env
        sed -i "s/DB_PASSWORD=/DB_PASSWORD=${{ secrets.DB_PASSWORD }}/g" .env

    - name: Display .env content
      run: cat .env

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: g21be.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_aa61053aeea04480a2622e2dd49bf5d9 }}/g21-be:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'g21-be'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a741e975cdc34876bb2c89b93325a435 }}
        images: 'g21be.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_aa61053aeea04480a2622e2dd49bf5d9 }}/g21-be:${{ github.sha }}'